### ISSUE TITLE
Simplest googletest installation

### ISSUE THREAD

**Issue by Lecrapouille** [bastianhjaeger/github_actions_gtest_example#2]
I've tried your yaml file to install google test for my own project but I did not succeeded
```
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
```

Was not working for me. Here is my way:
```
      - name: Install googletest manually
        run: |
          wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
          tar xf release-1.10.0.tar.gz
          (cd googletest-release-1.10.0 &&
          cmake -DBUILD_SHARED_LIBS=ON . &&
          sudo make install)
```

You maybe need to install wget:
```
sudo apt-get install wget
```

And my rule is also working for Mac OS X
```
  build-macosx:
    name: MacOS X Build
    runs-on: macos-latest
    steps:
      - name: Install system packages
        run: brew install wget

      - name: Install googletest manually
... same code
```

(I've not tried for Window)
